# frozen_string_literal: true

# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  property :primary_identifier, predicate: ::RDF::Vocab::DC11.identifier, multiple: false do |index|
    index.as :stored_sortable
  end
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  self.indexer = Hyrax::CollectionWithBasicMetadataIndexer

  def self.terms
    @metadata ||= properties.keys.sort.map(&:to_sym)
  end

  def self.required_terms
    @required_metadata ||= Hyrax::Forms::CollectionForm.required_fields.sort
  end

  def self.editable_terms
    @editable_metadata ||= Hyrax::Forms::CollectionForm.terms.sort
  end
end
